<!-- Message de notification -->

<!-- Code HTML à écrire -->



<!-- Liste des aliments -->

<table class="generic-table meal-list">
    <caption>Carte du restaurant</caption>
    <tbody>


<?php foreach ($productList AS $product):?>
		<tr>
			<td><img src="<?= $wwwUrl ?>/<?=$product['url_img']?>"></td>
			<td><h4><?=$product['name']?></h4></td>
			<td><?=$product['description']?></td>
			<td><strong><?= Tools::getPriceFormated($product['priceHT']) ?></strong></td>

		</tr>
<?php endforeach ?>
        
    </tbody>
</table>