<!-- Message de notification -->

<!-- Code HTML à écrire -->


<!-- Liste des aliments -->

<table class="generic-table meal-list">
    <caption>Carte du restaurant</caption>
    <tbody>
     	<tr>   <!-- Code HTML à écrire -->
<!-- <?php foreach ($tableauProducts AS $product):?>
			<td><img src="<?= $wwwUrl ?>/<?=$product['url_img']?>"></td>
			<td><h4><?=$product['name']?></h4></td>
			<td><?=$product['description']?></td>
			<td><strong><?=$product['tax']?> €</strong></td>
		</tr>
<?php endforeach ?> -->
        
    </tbody>
</table>