
<?php 
print_r($_SESSION);
?>
<h2>Passer une commande</h2>

<form class="generic-form" action="<?=$requestUrl?>/cart" method="POST">
    <fieldset>
        <legend>Ajouter un article</legend>
        <ul>
            <li>
                <label class="generic-form ul li label:not(no-width)" for="meal">Nom :</label>

                <select id="meal" name="meal" class="generic-form select">
<?php 
    
    foreach($productList AS $product):?>
                <option value="<?=$product['id']?>"><?=$product['name']?></option>
<?php 
endforeach

?>
                </select>
            <article id="meal-details" class="meal-details no-left-label">
            </article>    
            </li>
            <li>
                <label for="quantity">Quantité :</label>
                <input id="quantity" class="quantity" type="text" maxlength="2" name="quantity" data-name="Quantité" data-type="positive-integer" data-required>
            </li>
            <li>
                <button class="button button-primary no-left-label" type="button">Ajouter</button>
            </li>
        </ul>
    </fieldset>

   <fieldset>
        <legend>Récapitulatif de la commande</legend>
        <section id="order-recap">
            
        </section>
    </fieldset>
</form>

<ul class="link-list">
    <li>
        <button id="validate-order" class="button button-primary">Valider la commande</button>
        <a class="button button-cancel small" href="/dev/resto/final/index.php">Annuler</a>
    </li>
</ul>

<script src="<?= $wwwUrl ?>/js/order.js"></script>

