
    <h2>Se connecter avec un compte utilisateur</h2>
<form class="generic-form" action="" method="POST">
	<fieldset>
		<legend>Informations d'authentification</legend>
		<ul>
			<li>
				<label>E-mail</label>
				<input type="mail" class='generic-form input[type="text"]' name="mail"><br>
				<br>
			</li>
			<li>
				<label>Mot de passe</label>
				<input type="password" class='generic-form input[type="password"]' name="password">
			</li>
		</ul>
	</fieldset>
	<button type="submit" class="button button-primary">Connexion</button>
	<button type="reset" class="button button-cancel">Annuler</button>
 </form>